/**
 * Regenerates docs/TEST-SCORES.md and docs/BENCHMARK.md from the harness's own JSON output,
 * so per-case tables can't drift from generator.ts or go stale after a scoring change.
 *
 * Prerequisites (run first, freshest last):
 *   npm run test:suite       → output/suite/results.json           (required)
 *   npm run test:benchmark   → output/benchmark/results-*.json     (required for BENCHMARK.md)
 *
 * Optional, included only if present:
 *   tsx tools/style-source-benchmark.ts  → output/benchmark/style-source/results-dom-docx-computed.json
 *   tsx tools/css-cascade-runner.ts      → output/css-cascade/results.json
 *   npm run test:calibration             → output/suite/calibration.json
 *   internal/research/human-labels.json  (gitignored, maintainer-local blind ratings)
 *
 * Run: npm run docs:sync
 */
import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  generateEdgeTestCases,
  generateStandardTestCases,
  generateTestCases,
  type TestCase,
} from "./generator.js";
import { BENCHMARK_LIBRARIES } from "./benchmark/libraries.js";
import type { SuiteRollup } from "./scoring.js";
import type { CaseResult, LoopResults } from "./validator.js";
import type { BenchmarkResults } from "./benchmark-runner.js";
import type { StyleSourceComparisonResults } from "./style-source-benchmark.js";
import type { CssCascadeResults } from "./css-cascade-runner.js";
import type { CalibrationResults } from "./calibration-runner.js";
import { SUITE_OUTPUT, BENCHMARK_OUTPUT, CSS_CASCADE_OUTPUT } from "./output-paths.js";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOCS_DIR = path.join(REPO_ROOT, "docs");
const TEST_SCORES_PATH = path.join(DOCS_DIR, "TEST-SCORES.md");
const BENCHMARK_PATH = path.join(DOCS_DIR, "BENCHMARK.md");

const SUITE_RESULTS_PATH = path.join(SUITE_OUTPUT, "results.json");
const CALIBRATION_PATH = path.join(SUITE_OUTPUT, "calibration.json");
const STYLE_SOURCE_PATH = path.join(BENCHMARK_OUTPUT, "style-source", "results-dom-docx-computed.json");
const CSS_CASCADE_PATH = path.join(CSS_CASCADE_OUTPUT, "results.json");
const HUMAN_LABELS_PATH = path.join(REPO_ROOT, "internal", "research", "human-labels.json");

const GENERATED_NOTICE =
  "<!-- Generated by `npm run docs:sync` from output/suite + output/benchmark JSON. Do not hand-edit — edit tools/docs-sync.ts or tools/generator.ts (case descriptions) instead. -->";

function printPrerequisites(): void {
  console.log("docs:sync — regenerates docs/TEST-SCORES.md and docs/BENCHMARK.md");
  console.log("");
  console.log("Prerequisites (run first if the JSON below is missing or stale):");
  console.log("  npm run test:suite       → output/suite/results.json");
  console.log("  npm run test:benchmark   → output/benchmark/results-*.json");
  console.log("");
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJson<T>(filePath: string): Promise<T | null> {
  if (!(await fileExists(filePath))) return null;
  return JSON.parse(await readFile(filePath, "utf-8")) as T;
}

function fmtPct(value: number | null | undefined): string {
  return value !== null && value !== undefined ? `${value.toFixed(2)}%` : "—";
}

function fmtScore(value: number | null | undefined): string {
  return value !== null && value !== undefined ? value.toFixed(2) : "—";
}

function fmtMs(value: number | null | undefined): string {
  return value !== null && value !== undefined ? `${value.toFixed(1)} ms` : "—";
}

function fmtDelta(value: number | null | undefined): string {
  if (value === null || value === undefined) return "—";
  return `${value >= 0 ? "+" : ""}${value.toFixed(2)}`;
}

/** Human-readable age, e.g. "2h 15m", "3d 4h". Used for staleness warnings only. */
function humanAge(ms: number): string {
  const abs = Math.abs(ms);
  const minutes = Math.floor(abs / 60_000);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ${hours % 24}h`;
  if (hours > 0) return `${hours}h ${minutes % 60}m`;
  return `${minutes}m`;
}

function rollup(cases: CaseResult[]): SuiteRollup {
  const completed = cases.filter((c) => !c.error);
  const avg = (values: Array<number | null | undefined>): number | null => {
    const nums = values.filter((v): v is number => v !== null && v !== undefined);
    return nums.length > 0 ? nums.reduce((s, v) => s + v, 0) / nums.length : null;
  };
  return {
    caseCount: cases.length,
    completedCount: completed.length,
    xmlPassCount: cases.filter((c) => c.xmlPassed).length,
    visual: avg(completed.map((c) => c.visualScore)),
    editability: avg(completed.map((c) => c.editability)),
    performance: avg(completed.map((c) => c.performanceScore)),
    engine: avg(completed.map((c) => c.engineScore)),
    avgPerformanceMs: avg(completed.map((c) => c.compileMs)),
    layout: avg(completed.map((c) => c.layoutFidelityScore)),
    pixelMatch: avg(completed.map((c) => c.matchPercent)),
  };
}

// ---------------------------------------------------------------------------
// TEST-SCORES.md
// ---------------------------------------------------------------------------

function caseTable(cases: CaseResult[], descriptions: Map<string, string>): string {
  const rows = cases.map((c) => {
    const desc = descriptions.get(c.name);
    const flaggedName = desc ? c.name : `${c.name} ⚠️ no description in generator.ts`;
    const xml = c.error ? "ERR" : c.xmlPassed ? "✓" : "✗";
    const misaligned = c.mismatchedPixels !== undefined ? c.mismatchedPixels.toLocaleString() : "—";
    return `| \`${flaggedName}\` | ${desc ?? "—"} | ${xml} | ${fmtPct(c.visualScore)} | ${misaligned} |`;
  });
  return [
    "| Test | Description | XML | Visual | Misaligned px |",
    "|------|-------------|-----|--------|---------------|",
    ...rows,
  ].join("\n");
}

async function buildTestScoresMd(suiteResults: LoopResults): Promise<string> {
  const standardNames = new Set(generateStandardTestCases().map((c) => c.name));
  const descriptions = new Map(generateTestCases().map((c) => [c.name, c.description ?? ""]));

  const standardCases = suiteResults.cases.filter((c) => standardNames.has(c.name));
  const edgeCases = suiteResults.cases.filter((c) => !standardNames.has(c.name));
  const allRollup = suiteResults.suite;
  const standardRollup = rollup(standardCases);
  const edgeRollup = rollup(edgeCases);

  const calibration = await readJson<CalibrationResults>(CALIBRATION_PATH);
  const calibrationRow = calibration
    ? `| Identity-pair calibration (full ${calibration.cases.length}) | — | — | **mean ${fmtPct(calibration.meanAdjustedCeiling)} / min ${fmtPct(calibration.minAdjustedCeiling)}** |`
    : null;

  const humanLabels = await readJson<{ labels: Record<string, { rating?: number; note?: string }> }>(
    HUMAN_LABELS_PATH,
  );

  const lowest = [...suiteResults.cases]
    .filter((c) => c.visualScore !== null)
    .sort((a, b) => (a.visualScore ?? 0) - (b.visualScore ?? 0))
    .slice(0, 8);

  const hasHumanLabels = humanLabels && lowest.some((c) => humanLabels.labels[c.name]?.rating);
  const lowestHeader = hasHumanLabels
    ? "| Test | Visual | Human | Notes |\n|------|-------:|:-----:|-------|"
    : "| Test | Visual | Notes |\n|------|-------:|-------|";
  const lowestRows = lowest.map((c) => {
    const desc = descriptions.get(c.name) ?? "—";
    if (hasHumanLabels) {
      const label = humanLabels!.labels[c.name];
      return `| \`${c.name}\` | ${fmtPct(c.visualScore)} | ${label?.rating ?? "—"} | ${label?.note ?? desc} |`;
    }
    return `| \`${c.name}\` | ${fmtPct(c.visualScore)} | ${desc} |`;
  });

  return `# Validation scores

${GENERATED_NOTICE}

To generate suite metrics, run \`npm run test:suite\` then \`npm run docs:sync\`. **How scores are computed:** [SCORING.md](./SCORING.md).

Last regenerated from a suite run at **${suiteResults.runAt}** (mode: ${suiteResults.mode}).

## Summary

| Metric | Standard (${standardCases.length}) | Edge (${edgeCases.length}) | All (${suiteResults.cases.length}) |
|--------|---------------|-----------|----------|
| XML schema pass | ${standardRollup.xmlPassCount} / ${standardCases.length} | ${edgeRollup.xmlPassCount} / ${edgeCases.length} | **${allRollup.xmlPassCount} / ${suiteResults.cases.length}** |
| Avg **visual (layout-based)** | ${fmtPct(standardRollup.visual)} | ${fmtPct(edgeRollup.visual)} | **${fmtPct(allRollup.visual)}** |
| Avg raw layout (pre-guards) | ${fmtPct(standardRollup.layout)} | ${fmtPct(edgeRollup.layout)} | **${fmtPct(allRollup.layout)}** |
| Avg pixel match (tripwire, unscored) | ${fmtPct(standardRollup.pixelMatch)} | ${fmtPct(edgeRollup.pixelMatch)} | **${fmtPct(allRollup.pixelMatch)}** |
| Avg engine score | ${fmtScore(standardRollup.engine)} | ${fmtScore(edgeRollup.engine)} | **${fmtScore(allRollup.engine)}** |
| Avg compile | — | — | **${fmtMs(allRollup.avgPerformanceMs)}** |
${calibrationRow ?? "| Identity-pair calibration | — | — | _run `npm run test:calibration` for this row_ |"}

Tables below use the **layout-based visual** score; misaligned px is the raw pixel tripwire.

---

## Standard baseline (${standardCases.length})

${caseTable(standardCases, descriptions)}

## Edge cases (${edgeCases.length})

${caseTable(edgeCases, descriptions)}

---

## Lowest scores (current priorities)

Bottom ${lowest.length} cases by layout-based visual score${hasHumanLabels ? " — human rating (1 = looks right, 2 = minor, 3 = broken) from `internal/research/human-labels.json`" : ""}:

${lowestHeader}
${lowestRows.join("\n")}

---

## Related

- **OSS comparison** — run \`npm run test:benchmark\` after a loop; see [BENCHMARK.md](./BENCHMARK.md)
- **Regenerate** — \`npm run test:suite\` (full) or \`npm run test:suite:priority\` (10-case subset), then \`npm run docs:sync\`
`;
}

// ---------------------------------------------------------------------------
// BENCHMARK.md
// ---------------------------------------------------------------------------

function benchmarkCaseTable(
  cases: BenchmarkResults["cases"],
  libraryLabel: string,
): string {
  const sorted = [...cases].sort((a, b) => (a.deltaVisual ?? 0) - (b.deltaVisual ?? 0));
  const rows = sorted.map((c) => {
    const xml = c.error ? "ERR" : c.xmlPassed ? "✓" : "✗";
    return `| \`${c.name}\` | ${xml} | ${fmtPct(c.visualScore)} | ${fmtPct(c.domDocx?.visualScore)} | ${fmtDelta(c.deltaVisual)} |`;
  });
  return [
    `| Test | XML (${libraryLabel}) | ${libraryLabel} visual | dom-docx visual | Δ (${libraryLabel} − dom-docx) |`,
    "|------|:---:|-------:|-------:|--:|",
    ...rows,
  ].join("\n");
}

function listComparisonTable(
  suiteResults: LoopResults,
  benchmarks: Array<{ id: string; label: string; payload: BenchmarkResults }>,
): string | null {
  const listCases = suiteResults.cases.filter(
    (c) => c.htmlMarkerLineCount !== undefined && c.htmlMarkerLineCount > 0,
  );
  if (listCases.length === 0) return null;

  const header = [
    `| Library | ${listCases.map((c) => `\`${c.name}\``).join(" | ")} |`,
    `|---------|${listCases.map(() => "---:").join("|")}|`,
  ];
  const domDocxRow = `| dom-docx | ${listCases.map((c) => `**${fmtPct(c.visualScore)}**`).join(" | ")} |`;
  const libRows = benchmarks.map(({ label, payload }) => {
    const byName = new Map(payload.cases.map((c) => [c.name, c]));
    return `| ${label} | ${listCases.map((c) => fmtPct(byName.get(c.name)?.visualScore)).join(" | ")} |`;
  });

  return [...header, domDocxRow, ...libRows].join("\n");
}

async function buildBenchmarkMd(
  suiteResults: LoopResults,
  benchmarks: Array<{ id: string; label: string; payload: BenchmarkResults }>,
): Promise<string> {
  const domDocxSuite = suiteResults.suite;
  const caseCount = suiteResults.cases.length;

  const librariesTable = [
    "| ID | Package | Version | Notes |",
    "|----|---------|---------|-------|",
    ...benchmarks.map(
      ({ payload }) =>
        `| \`${payload.library.id}\` | [\`${payload.library.npm}\`](https://www.npmjs.com/package/${payload.library.npm}) | ${payload.library.version} | ${payload.library.description} |`,
    ),
  ].join("\n");

  const summaryTable = [
    `| Metric | ${benchmarks.map((b) => b.label).join(" | ")} | dom-docx |`,
    `|--------|${benchmarks.map(() => "---:").join("|")}|---:|`,
    `| XML schema pass | ${benchmarks.map((b) => `${b.payload.suite.xmlPassCount} / ${caseCount}`).join(" | ")} | **${domDocxSuite.xmlPassCount} / ${caseCount}** |`,
    `| Avg **visual (layout-based)** | ${benchmarks.map((b) => fmtPct(b.payload.suite.visual)).join(" | ")} | **${fmtPct(domDocxSuite.visual)}** |`,
    `| Avg editability | ${benchmarks.map((b) => fmtScore(b.payload.suite.editability)).join(" | ")} | ${fmtScore(domDocxSuite.editability)} |`,
    `| Avg engine score | ${benchmarks.map((b) => fmtScore(b.payload.suite.engine)).join(" | ")} | **${fmtScore(domDocxSuite.engine)}** |`,
    `| Avg compile | ${benchmarks.map((b) => fmtMs(b.payload.suite.avgPerformanceMs)).join(" | ")} | ${fmtMs(domDocxSuite.avgPerformanceMs)} |`,
  ].join("\n");

  const deltaTable = [
    "| Library | Δ visual | Δ engine |",
    "|---------|---------:|---------:|",
    ...benchmarks.map(
      (b) => `| ${b.label} | **${fmtDelta(b.payload.comparison.delta.visual)}** | ${fmtDelta(b.payload.comparison.delta.engine)} |`,
    ),
  ].join("\n");

  const winCounts = benchmarks.map((b) => {
    const wins = b.payload.cases.filter((c) => (c.deltaVisual ?? 0) < 0).length;
    return `**dom-docx wins ${wins} / ${caseCount} cases** against ${b.label} (higher layout-based visual score).`;
  });

  const perCaseSections = benchmarks
    .map(
      ({ label, payload }) => `### ${label} vs dom-docx — per case

${benchmarkCaseTable(payload.cases, label)}`,
    )
    .join("\n\n");

  const listTable = listComparisonTable(suiteResults, benchmarks);

  const styleSource = await readJson<StyleSourceComparisonResults>(STYLE_SOURCE_PATH);
  const styleSourceSection = styleSource
    ? `## Style source: inline vs computed-oracle vs computed-native (dom-docx)

Last regenerated from a run at **${styleSource.runAt}**.

| Metric | inline | computed-oracle | computed-native |
|--------|-------:|----------------:|----------------:|
| Avg **adjusted** visual | ${fmtPct(styleSource.inline.suite?.visual)} | ${fmtPct(styleSource.computed.suite.visual)} | ${fmtPct(styleSource.computedNative.suite.visual)} |
| Avg engine score | ${fmtScore(styleSource.inline.suite?.engine)} | ${fmtScore(styleSource.computed.suite.engine)} | ${fmtScore(styleSource.computedNative.suite.engine)} |
| Avg compile | ${fmtMs(styleSource.inline.suite?.avgPerformanceMs)} | ${fmtMs(styleSource.comparisonNative.avgCompileMsOracle)} | ${fmtMs(styleSource.comparisonNative.avgCompileMsNative)} |

Δ native − oracle (visual): ${fmtDelta(styleSource.comparisonNative.deltaVisualVsOracle)}. Regenerate: \`tsx tools/style-source-benchmark.ts\` (needs a fresh \`npm run test:suite\` baseline).`
    : `## Style source: inline vs computed-oracle vs computed-native (dom-docx)

Not yet generated in this run. Regenerate: \`tsx tools/style-source-benchmark.ts\` (needs a fresh \`npm run test:suite\` baseline first).`;

  const cssCascade = await readJson<CssCascadeResults>(CSS_CASCADE_PATH);
  const cssCascadeSection = cssCascade
    ? `## CSS cascade suite (stylesheet / class selectors)

Last regenerated from a run at **${cssCascade.runAt}**. Cases: \`tools/css-cascade-cases.ts\` · Output: \`output/css-cascade/results.json\`

| Metric | inline | computed | Δ |
|--------|-------:|---------:|--:|
| Avg adjusted visual | ${fmtPct(cssCascade.suite.inline.visual)} | ${fmtPct(cssCascade.suite.computed.visual)} | **${fmtDelta(cssCascade.suite.deltaVisual)}** |
| Cases passed | — | ${cssCascade.summary.passedCount} / ${cssCascade.summary.caseCount} | — |

Regenerate: \`tsx tools/css-cascade-runner.ts\`.`
    : `## CSS cascade suite (stylesheet / class selectors)

Not yet generated in this run. Regenerate: \`tsx tools/css-cascade-runner.ts\`.`;

  return `# Benchmark: OSS HTML→DOCX vs dom-docx

${GENERATED_NOTICE}

Generate via \`npm run test:suite && npm run test:benchmark && npm run docs:sync\`.

All libraries use the **same visual harness**: human-validated layout fidelity plus content-quality guards (legibility, background balance, list marker fidelity, text content fidelity). List marker checks run only when HTML contains \`<ol>\`/\`<ul>\`. Raw pixel match is recorded per case as a regression tripwire but contributes to no score. See [SCORING.md](./SCORING.md).

Last regenerated from a dom-docx suite run at **${suiteResults.runAt}**; per-library benchmark runs at ${benchmarks.map((b) => `**${b.payload.runAt}** (${b.label})`).join(", ")}.

## Libraries under test

${librariesTable}

---

## Suite summary (${caseCount} cases)

${summaryTable}

Δ vs dom-docx (library − dom-docx):

${deltaTable}

${winCounts.join("\n")}

---

${perCaseSections}
${listTable ? `\n### List comparison (layout-based visual)\n\n${listTable}\n\n---` : ""}

${styleSourceSection}

---

${cssCascadeSection}

---

## Commands

\`\`\`bash
npm run test:suite                  # refresh dom-docx baseline (run before benchmark)
npm run test:benchmark              # all OSS libraries
npm run test:benchmark -- turbodocx
npm run test:benchmark -- html-to-docx
npm run docs:sync                   # regenerate this file + TEST-SCORES.md
npm run test:inline-guard           # assert inline default unchanged
\`\`\`

Style-source, CSS-cascade, and parity guards: [CONTRIBUTING.md](../CONTRIBUTING.md#maintainer-only-harness-commands).

## Artifacts

\`\`\`
output/
  suite/                       # test:suite — standard baseline + edge cases
  benchmark/                   # test:benchmark, style-source
    results.json
    results-html-to-docx.json
    results-turbodocx.json
    html-to-docx/{name}/
    turbodocx/{name}/
    style-source/
  showcase/                    # test:showcase scratch (committed copies in examples/)
  css-cascade/                 # tsx tools/css-cascade-runner.ts
\`\`\`

Adapters: \`tools/benchmark/html-to-docx-adapter.ts\`, \`tools/benchmark/turbodocx-adapter.ts\` · Style source: \`tools/style-source-benchmark.ts\`

## Related

| Doc | Contents |
|-----|----------|
| [SCORING.md](./SCORING.md) | Validation methodology and engine score |
| [TEST-SCORES.md](./TEST-SCORES.md) | dom-docx-only suite metrics |
`;
}

// ---------------------------------------------------------------------------
// Staleness checks
// ---------------------------------------------------------------------------

const STALE_THRESHOLD_MS = 60 * 60 * 1000; // 1 hour

function checkStaleness(
  suiteResults: LoopResults,
  benchmarks: Array<{ id: string; label: string; payload: BenchmarkResults }>,
): string[] {
  const warnings: string[] = [];
  const suiteTime = new Date(suiteResults.runAt).getTime();

  for (const { label, payload } of benchmarks) {
    const comparedAgainst = payload.comparison.domDocxRunAt;
    if (!comparedAgainst) {
      warnings.push(
        `${label}'s benchmark run has no dom-docx baseline recorded — its comparison columns will be blank. Run npm run test:suite first, then re-run npm run test:benchmark.`,
      );
      continue;
    }
    const comparedTime = new Date(comparedAgainst).getTime();
    if (comparedTime !== suiteTime) {
      const gap = suiteTime - comparedTime;
      const newer = gap > 0 ? "dom-docx suite" : label;
      warnings.push(
        `${label}'s benchmark was compared against a dom-docx baseline from ${comparedAgainst}, but the current suite results are from ${suiteResults.runAt} (${humanAge(gap)} ${newer} is newer). Re-run npm run test:benchmark to refresh the comparison.`,
      );
    } else if (Math.abs(suiteTime - new Date(payload.runAt).getTime()) > STALE_THRESHOLD_MS) {
      warnings.push(
        `${label}'s benchmark run (${payload.runAt}) is ${humanAge(suiteTime - new Date(payload.runAt).getTime())} apart from the dom-docx suite run (${suiteResults.runAt}). Consider re-running both back-to-back for a consistent snapshot.`,
      );
    }
  }

  return warnings;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  printPrerequisites();

  const suiteResults = await readJson<LoopResults>(SUITE_RESULTS_PATH);
  if (!suiteResults) {
    console.error(`Missing ${path.relative(REPO_ROOT, SUITE_RESULTS_PATH)} — run npm run test:suite first.`);
    process.exitCode = 1;
    return;
  }

  const missingDescriptions = generateTestCases().filter((c) => !c.description);
  if (missingDescriptions.length > 0) {
    console.warn(
      `Warning: ${missingDescriptions.length} case(s) in generator.ts have no description and will be flagged in TEST-SCORES.md: ${missingDescriptions.map((c) => c.name).join(", ")}`,
    );
  }

  await writeFile(TEST_SCORES_PATH, await buildTestScoresMd(suiteResults), "utf-8");
  console.log(`Wrote ${path.relative(REPO_ROOT, TEST_SCORES_PATH)}`);

  const benchmarks: Array<{ id: string; label: string; payload: BenchmarkResults }> = [];
  for (const lib of BENCHMARK_LIBRARIES) {
    const resultsPath = path.join(BENCHMARK_OUTPUT, `results-${lib.id}.json`);
    const payload = await readJson<BenchmarkResults>(resultsPath);
    if (payload) {
      benchmarks.push({ id: lib.id, label: payload.library.npm, payload });
    } else {
      console.warn(
        `Warning: no benchmark results for "${lib.id}" (${path.relative(REPO_ROOT, resultsPath)} not found) — it will be missing from BENCHMARK.md. Run npm run test:benchmark.`,
      );
    }
  }

  if (benchmarks.length === 0) {
    console.error(
      `No benchmark results found under ${path.relative(REPO_ROOT, BENCHMARK_OUTPUT)} — skipping BENCHMARK.md. Run npm run test:benchmark first.`,
    );
    process.exitCode = 1;
    return;
  }

  const staleWarnings = checkStaleness(suiteResults, benchmarks);
  if (staleWarnings.length > 0) {
    console.warn("\nStaleness warnings:");
    for (const w of staleWarnings) console.warn(`  - ${w}`);
    console.warn("");
  }

  await writeFile(BENCHMARK_PATH, await buildBenchmarkMd(suiteResults, benchmarks), "utf-8");
  console.log(`Wrote ${path.relative(REPO_ROOT, BENCHMARK_PATH)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
